"""Schema definitions and dataframe-level validation helpers."""

from __future__ import annotations

import json
from pathlib import Path

import pandas as pd

from .models import RunMetadata


CONTRACT_SCHEMAS: dict[str, dict[str, object]] = {
    "fact_attribution": {
        "title": "FactAttribution",
        "required": [
            "schema_version",
            "metric_version",
            "run_id",
            "business_subject_key",
            "_lead_key",
            "线索ID",
            "手机号",
            "线索创建时间",
            "date",
            "标准账号",
            "归属状态",
            "is_order",
            "is_deal",
        ],
        "properties": {
            "schema_version": {"type": "string"},
            "metric_version": {"type": "string"},
            "run_id": {"type": "string"},
            "business_subject_key": {"type": "string"},
            "_lead_key": {"type": "string"},
            "线索ID": {"type": "string"},
            "手机号": {"type": "string"},
            "线索创建时间": {"type": "string"},
            "date": {"type": "string"},
            "标准账号": {"type": "string"},
            "本场主播": {"type": "string"},
            "归属状态": {"type": "string"},
            "无匹配原因": {"type": "string"},
            "is_order": {"type": "integer"},
            "is_deal": {"type": "integer"},
        },
    },
    "daily_performance_snapshot": {
        "title": "DailyPerformanceSnapshot",
        "required": [
            "schema_version",
            "metric_version",
            "run_id",
            "snapshot_date",
            "report_month",
            "date",
            "scope_type",
            "scope_name",
            "parent_account",
            "daily_leads",
            "mtd_leads",
            "daily_deals",
            "mtd_deals",
            "mtd_spend",
            "lead_target_month",
            "deal_target_month",
        ],
        "properties": {
            "schema_version": {"type": "string"},
            "metric_version": {"type": "string"},
            "run_id": {"type": "string"},
            "snapshot_date": {"type": "string"},
            "report_month": {"type": "string"},
            "date": {"type": "string"},
            "scope_type": {"type": "string"},
            "scope_name": {"type": "string"},
            "parent_account": {"type": "string"},
            "daily_leads": {"type": "number"},
            "mtd_leads": {"type": "number"},
            "daily_deals": {"type": "number"},
            "mtd_deals": {"type": "number"},
            "mtd_spend": {"type": "number"},
            "lead_target_month": {"type": "number"},
            "deal_target_month": {"type": "number"},
        },
    },
    "compensation_ledger": {
        "title": "CompensationLedger",
        "required": [
            "schema_version",
            "metric_version",
            "run_id",
            "settlement_period",
            "freeze_id",
            "scope_type",
            "scope_name",
            "parent_account",
            "snapshot_start",
            "snapshot_end",
            "mtd_leads",
            "mtd_deals",
            "mtd_spend",
            "mtd_cpl",
            "mtd_cps",
            "lead_target_month",
            "deal_target_month",
            "lead_attain_pct",
            "deal_attain_pct",
            "formula_name",
            "formula_inputs_json",
            "ledger_status",
        ],
        "properties": {
            "schema_version": {"type": "string"},
            "metric_version": {"type": "string"},
            "run_id": {"type": "string"},
            "settlement_period": {"type": "string"},
            "freeze_id": {"type": "string"},
            "scope_type": {"type": "string"},
            "scope_name": {"type": "string"},
            "parent_account": {"type": "string"},
            "snapshot_start": {"type": "string"},
            "snapshot_end": {"type": "string"},
            "mtd_leads": {"type": "number"},
            "mtd_deals": {"type": "number"},
            "mtd_spend": {"type": "number"},
            "mtd_cpl": {"type": "number"},
            "mtd_cps": {"type": "number"},
            "lead_target_month": {"type": "number"},
            "deal_target_month": {"type": "number"},
            "lead_attain_pct": {"type": "number"},
            "deal_attain_pct": {"type": "number"},
            "formula_name": {"type": "string"},
            "formula_inputs_json": {"type": "string"},
            "ledger_status": {"type": "string"},
        },
    },
    "analysis_snapshot": {
        "title": "AnalysisSnapshot",
        "required": [
            "schema_version",
            "metric_version",
            "run_id",
            "snapshot_date",
            "analysis_mode",
            "evidence_mode",
            "subject_area",
            "topic_name",
            "table_name",
            "grain",
            "dimension_key",
            "metric_name",
            "metric_value",
            "raw_evidence_required",
            "source_scope",
        ],
        "properties": {
            "schema_version": {"type": "string"},
            "metric_version": {"type": "string"},
            "run_id": {"type": "string"},
            "snapshot_date": {"type": "string"},
            "analysis_mode": {"type": "string"},
            "evidence_mode": {"type": "string"},
            "subject_area": {"type": "string"},
            "topic_name": {"type": "string"},
            "table_name": {"type": "string"},
            "grain": {"type": "string"},
            "dimension_key": {"type": "string"},
            "metric_name": {"type": "string"},
            "metric_value": {"type": "number"},
            "raw_evidence_required": {"type": "boolean"},
            "source_scope": {"type": "string"},
            "migration_status": {"type": "string"},
        },
    },
    "raw_analysis_snapshot": {
        "title": "RawAnalysisSnapshot",
        "required": [
            "schema_version",
            "metric_version",
            "run_id",
            "snapshot_date",
            "analysis_mode",
            "evidence_mode",
            "subject_area",
            "topic_name",
            "table_name",
            "grain",
            "dimension_key",
            "metric_name",
            "metric_value",
            "raw_evidence_required",
            "source_scope",
        ],
        "properties": {
            "schema_version": {"type": "string"},
            "metric_version": {"type": "string"},
            "run_id": {"type": "string"},
            "snapshot_date": {"type": "string"},
            "analysis_mode": {"type": "string"},
            "evidence_mode": {"type": "string"},
            "subject_area": {"type": "string"},
            "topic_name": {"type": "string"},
            "table_name": {"type": "string"},
            "grain": {"type": "string"},
            "dimension_key": {"type": "string"},
            "metric_name": {"type": "string"},
            "metric_value": {"type": "number"},
            "raw_evidence_required": {"type": "boolean"},
            "source_scope": {"type": "string"},
            "migration_status": {"type": "string"},
        },
    },
    "export_manifest": {
        "title": "ExportManifest",
        "required": [
            "schema_version",
            "metric_version",
            "run_id",
            "export_name",
            "snapshot_date",
            "template_version",
            "freeze_id",
            "source_tables",
            "row_count",
            "generated_at",
            "consumer",
            "output_path",
        ],
        "properties": {
            "schema_version": {"type": "string"},
            "metric_version": {"type": "string"},
            "run_id": {"type": "string"},
            "export_name": {"type": "string"},
            "snapshot_date": {"type": "string"},
            "template_version": {"type": "string"},
            "freeze_id": {"type": "string"},
            "source_tables": {"type": "array", "items": {"type": "string"}},
            "row_count": {"type": "integer"},
            "generated_at": {"type": "string"},
            "consumer": {"type": "string"},
            "output_path": {"type": "string"},
        },
    },
    "manual_attribution_override": {
        "title": "ManualAttributionOverride",
        "required": [
            "override_id",
            "business_subject_key",
            "phone",
            "lead_id",
            "override_scope",
            "target_account",
            "target_host",
            "reason",
            "evidence_note",
            "confirmed_by",
            "confirmed_at",
            "effective_from",
            "effective_to",
            "status",
            "metric_version",
            "run_id",
        ],
        "properties": {
            "override_id": {"type": "string"},
            "business_subject_key": {"type": "string"},
            "phone": {"type": "string"},
            "lead_id": {"type": "string"},
            "override_scope": {"type": "string"},
            "target_account": {"type": "string"},
            "target_host": {"type": "string"},
            "reason": {"type": "string"},
            "evidence_note": {"type": "string"},
            "confirmed_by": {"type": "string"},
            "confirmed_at": {"type": "string"},
            "effective_from": {"type": "string"},
            "effective_to": {"type": "string"},
            "status": {"type": "string"},
            "metric_version": {"type": "string"},
            "run_id": {"type": "string"},
        },
    },
    "manual_override_issue": {
        "title": "ManualOverrideIssue",
        "required": [
            "issue_id",
            "issue_type",
            "severity",
            "override_id",
            "business_subject_key",
            "phone",
            "lead_id",
            "detected_stage",
            "message_cn",
            "suggested_action",
            "status",
            "run_id",
        ],
        "properties": {
            "issue_id": {"type": "string"},
            "issue_type": {"type": "string"},
            "severity": {"type": "string"},
            "override_id": {"type": "string"},
            "business_subject_key": {"type": "string"},
            "phone": {"type": "string"},
            "lead_id": {"type": "string"},
            "detected_stage": {"type": "string"},
            "message_cn": {"type": "string"},
            "suggested_action": {"type": "string"},
            "status": {"type": "string"},
            "run_id": {"type": "string"},
            "matched_rows": {"type": "integer"},
            "conflict_override_ids": {"type": "array", "items": {"type": "string"}},
            "target_account": {"type": "string"},
            "target_host": {"type": "string"},
        },
    },
    "override_issue_daily_digest": {
        "title": "OverrideIssueDailyDigest",
        "required": [
            "run_id",
            "summary_status",
            "blocking_count",
            "warning_count",
            "info_count",
            "top_priority_issues",
            "account_impact_summary",
            "host_impact_summary",
            "latest_panel_risk_summary",
            "suggested_actions",
            "generated_at",
        ],
        "properties": {
            "run_id": {"type": "string"},
            "summary_status": {"type": "string"},
            "blocking_count": {"type": "integer"},
            "warning_count": {"type": "integer"},
            "info_count": {"type": "integer"},
            "top_priority_issues": {"type": "array", "items": {"type": "object"}},
            "account_impact_summary": {"type": "array", "items": {"type": "string"}},
            "host_impact_summary": {"type": "array", "items": {"type": "string"}},
            "latest_panel_risk_summary": {"type": "array", "items": {"type": "string"}},
            "suggested_actions": {"type": "array", "items": {"type": "string"}},
            "generated_at": {"type": "string"},
            "applied_override_count": {"type": "integer"},
            "applied_row_count": {"type": "integer"},
            "changed_final_consumer_scope": {"type": "boolean"},
        },
    },
}


def contract_required_columns(contract_name: str) -> list[str]:
    spec = CONTRACT_SCHEMAS[contract_name]
    return list(spec["required"])  # type: ignore[index]


def attach_contract_metadata(
    frame: pd.DataFrame,
    metadata: RunMetadata,
    *,
    template_version: str | None = None,
    freeze_id: str | None = None,
) -> pd.DataFrame:
    out = frame.copy()
    out["schema_version"] = metadata.schema_version
    out["metric_version"] = metadata.metric_version
    out["run_id"] = metadata.run_id
    if template_version is not None:
        out["template_version"] = template_version
    if freeze_id is not None:
        out["freeze_id"] = freeze_id
    return out


def validate_contract_frame(frame: pd.DataFrame, contract_name: str) -> list[str]:
    required = contract_required_columns(contract_name)
    return [column for column in required if column not in frame.columns]


def dump_contract_schemas(target_dir: Path) -> None:
    target_dir.mkdir(parents=True, exist_ok=True)
    for name, schema in CONTRACT_SCHEMAS.items():
        path = target_dir / f"{name}.schema.json"
        payload = {
            "$schema": "https://json-schema.org/draft/2020-12/schema",
            "type": "object",
            **schema,
        }
        path.write_text(json.dumps(payload, ensure_ascii=False, indent=2), encoding="utf-8")
